@startuml Diagrama de Sequência - Requisições MVC
hide footbox

actor ClienteWeb
actor ClienteMobile

control AdminController
control AutenticaController
control CategoriaController
control ClienteController
control FornecedorController
control ProdutoController
control RelatorioController

entity Admin
entity Categoria
entity Cliente
entity Fornecedor
entity Movimentacao
entity Produto
entity Relatorio
entity Usuario

database phpmyadmin

ClienteWeb -> AutenticaController: POST /logar
AutenticaController -> AdminController: logar()
AdminController -> AutenticaController: jsonUsuario
AutenticaController --> AdminController: jsonUsuario
AdminController -> phpmyadmin: jsonUsuario
phpmyadmin --> Admin
Admin --> AdminController
AdminController --> ClienteWeb

ClienteWeb -> AutenticaController: GET /listar
AdminController -> phpmyadmin: listar()
phpmyadmin --> Admin: jsonUsuario
Admin --> AdminController: jsonUsuario
AdminController --> ClienteWeb: jsonUsuario

ClienteWeb -> AdminController: POST /admin/excluir{id_usuario}
AdminController -> phpmyadmin: excluir()
phpmyadmin --> Admin: jsonUsuario{id_usuario}
Admin --> AdminController: jsonUsuario{id_usuario}
AdminController --> ClienteWeb: jsonUsuario{id_usuario}

ClienteWeb -> AutenticaController: POST /logar
AutenticaController -> phpmyadmin: logar()
phpmyadmin --> Cliente: jsonUsuario
Cliente --> AutenticaController: jsonUsuario
AutenticaController --> ClienteWeb: jsonUsuario

ClienteWeb -> AutenticaController: POST /logout
AutenticaController -> phpmyadmin: logout()
phpmyadmin --> Cliente: jsonUsuario
Cliente --> AutenticaController: jsonUsuario
AutenticaController --> ClienteWeb: jsonUsuario

ClienteWeb -> CategoriaController: GET /categorias
CategoriaController -> phpmyadmin: listarCategorias()
phpmyadmin --> Categoria: jsonCategorias
Categoria --> CategoriaController: jsonCategorias
CategoriaController --> ClienteWeb: jsonCategorias

ClienteWeb -> CategoriaController: GET /categorias/cadastro
CategoriaController -> phpmyadmin: prepararCadastroCategoria()
phpmyadmin --> Categoria
Categoria --> CategoriaController
CategoriaController --> ClienteWeb

ClienteWeb -> CategoriaController: POST /categorias/salvar{id_categoria}
CategoriaController -> phpmyadmin: salvarCategoria()
phpmyadmin --> Categoria: jsonCategoria{id_categoria}
Categoria --> CategoriaController: jsonCategoria{id_categoria}
CategoriaController --> ClienteWeb: jsonCategoria{id_categoria}

ClienteWeb -> CategoriaController: GET /categorias/atualizar&{id_categoria}
CategoriaController -> phpmyadmin: prepararEdicaoCategoria()
phpmyadmin --> Categoria: jsonCategoria{id_categoria}
Categoria --> CategoriaController: jsonCategoria{id_categoria}
CategoriaController --> ClienteWeb: jsonCategoria{id_categoria}

ClienteWeb -> CategoriaController: DELETE /categorias/excluir&{id_categoria}
CategoriaController -> phpmyadmin: excluirCategoria()
phpmyadmin --> Categoria: jsonCategoria{id_categoria}
Categoria --> CategoriaController: jsonCategoria{id_categoria}
CategoriaController --> ClienteWeb: jsonCategoria{id_categoria}

ClienteWeb -> ProdutoController: GET /produtos
ProdutoController -> phpmyadmin: listarProdutos()
phpmyadmin --> Produto: jsonProdutos
Produto --> ProdutoController: jsonProdutos
ProdutoController --> ClienteWeb: jsonProdutos

ClienteWeb -> ProdutoController: GET /produtos/cadastro
ProdutoController -> phpmyadmin: prepararCadastro()
phpmyadmin --> Produto
Produto --> ProdutoController
ProdutoController --> ClienteWeb

ClienteWeb -> ProdutoController: GET /produtos/editar&{id_produto}
ProdutoController -> phpmyadmin: prepararEdicaoProduto()
phpmyadmin --> Produto: jsonProduto{id_produto}
Produto --> ProdutoController: jsonProduto{id_produto}
ProdutoController --> ClienteWeb: jsonProduto{id_produto}

ClienteWeb -> ProdutoController: GET /produtos/atualizar&{id}
ProdutoController -> phpmyadmin: atualizarProduto()
phpmyadmin --> Produto: jsonProduto{id}
Produto --> ProdutoController: jsonProduto{id}
ProdutoController --> ClienteWeb: jsonProduto{id}

ClienteWeb -> ProdutoController: PUT /produtos/salvar&{id_produto}
ProdutoController -> phpmyadmin: salvarProduto()
phpmyadmin --> Produto: jsonProduto{id_produto}
Produto --> ProdutoController: jsonProduto{id_produto}
ProdutoController --> ClienteWeb: jsonProduto{id_produto}

ClienteWeb -> ProdutoController: POST /produtos/movimentar&{id_produto}
ProdutoController -> phpmyadmin: movimentar()
phpmyadmin --> Produto: jsonProduto{id_produto}
Produto --> ProdutoController: jsonProduto{id_produto}
ProdutoController --> ClienteWeb: jsonProduto{id_produto}

ClienteWeb -> ProdutoController: DELETE /produtos/excluir&{id_produto}
ProdutoController -> phpmyadmin: excluirProduto()
phpmyadmin --> Produto: jsonProduto{id_produto}
Produto --> ProdutoController: jsonProduto{id_produto}
ProdutoController --> ClienteWeb: jsonProduto{id_produto}

ClienteWeb -> FornecedorController: GET /fornecedores
FornecedorController -> phpmyadmin: listarFornecedores()
phpmyadmin --> Fornecedor: jsonFornecedores
Fornecedor --> FornecedorController: jsonFornecedores
FornecedorController --> ClienteWeb: jsonFornecedores

ClienteWeb -> FornecedorController: GET /fornecedores/cadastro
FornecedorController -> phpmyadmin: prepararCadastro()
phpmyadmin --> Fornecedor
Fornecedor --> FornecedorController
FornecedorController --> ClienteWeb

ClienteWeb -> FornecedorController: GET /fornecedores/editar&{id_fornecedor}
FornecedorController -> phpmyadmin: prepararEdicaoFornecedor()
phpmyadmin --> Fornecedor: jsonFornecedor{id_fornecedor}
Fornecedor --> FornecedorController: jsonFornecedor{id_fornecedor}
FornecedorController --> ClienteWeb: jsonFornecedor{id_fornecedor}

ClienteWeb -> FornecedorController: PUT /fornecedores/salvar&{id_fornecedor}
FornecedorController -> phpmyadmin: salvarFornecedor()
phpmyadmin --> Fornecedor: jsonFornecedores{id_fornecedor}
Fornecedor --> FornecedorController: jsonFornecedor{id_fornecedor}
FornecedorController --> ClienteWeb: jsonFornecedor{id_fornecedor}

ClienteWeb -> FornecedorController: DELETE /fornecedores/excluir&{id_fornecedor}
FornecedorController -> phpmyadmin: excluirFornecedor()
phpmyadmin --> Fornecedor: jsonFornecedor{id_fornecedor}
Fornecedor --> FornecedorController: jsonFornecedor{id_fornecedor}
FornecedorController --> ClienteWeb: jsonFornecedor{id_fornecedor}

ClienteWeb -> RelatorioController: GET /relatorios
RelatorioController -> phpmyadmin: prepararMenu()
phpmyadmin --> Relatorio: jsonRelatorios
Relatorio --> RelatorioController: jsonRelatorios
RelatorioController --> ClienteWeb: jsonRelatorios

ClienteWeb -> RelatorioController: GET /relatorios/estoque-total
RelatorioController -> phpmyadmin: gerarTotalEstoque()
phpmyadmin --> Relatorio: jsonRelatorios
Relatorio --> RelatorioController: jsonRelatorios
RelatorioController --> ClienteWeb: jsonRelatorios

ClienteWeb -> RelatorioController: GET /relatorios/historico
RelatorioController -> phpmyadmin: gerarHistorico()
phpmyadmin --> Relatorio: jsonRelatorios
Relatorio --> RelatorioController: jsonRelatorios
RelatorioController --> ClienteWeb: jsonRelatorios

ClienteWeb -> RelatorioController: GET /relatorios/mais-movimentados
RelatorioController -> phpmyadmin: gerarMaisMovimentados()
phpmyadmin --> Relatorio: jsonRelatorios
Relatorio --> RelatorioController: jsonRelatorios
RelatorioController --> ClienteWeb: jsonRelatorios

ClienteWeb -> ClienteController: GET /perfil
ClienteController -> phpmyadmin: perfil()
phpmyadmin --> Usuario: jsonUsuario
Usuario --> ClienteController: jsonUsuario
ClienteController --> ClienteWeb: jsonUsuario

ClienteWeb -> ClienteController: PUT /perfil/editar
ClienteController -> phpmyadmin: editar()
phpmyadmin --> Usuario: jsonUsuario
Usuario --> ClienteController: jsonUsuario
ClienteController --> ClienteWeb: jsonUsuario

ClienteWeb -> ClienteController: POST /perfil/atualizar
ClienteController -> phpmyadmin: atualizarPerfil()
phpmyadmin --> Usuario: jsonUsuario
Usuario --> ClienteController: jsonUsuario
ClienteController --> ClienteWeb: jsonUsuario

ClienteWeb -> ClienteController: GET /configuracoes
ClienteController -> phpmyadmin: configuracoes()
phpmyadmin --> Usuario
Usuario --> ClienteController
ClienteController --> ClienteWeb


@enduml